name: vendomed_flutter
description: "VendoMed app using Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.33.5

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets: #for adding images (need to declare it here)
    - assets/images/splash_logo.png
    - assets/images/ibuprofen.png
    - assets/images/paracetamol.png
    - assets/images/loperamide.png
    - assets/images/cetirizine.png
    - assets/userIcons/user_icon.png
  uses-material-design: true


